workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      java: 17
      node: 22
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web app
        script: npm run build
      - name: Sync Android
        script: npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
